### ISSUE TITLE
EPIC ART ISSUE

### ISSUE THREAD

**Issue by Achoobert** [Achoobert/game_4#10]
This is a wip list of all possible art assets we may need:

- [ ] NPC player art
  - [ ] Tyler 
    - [ ] Visual novel style
      - [x] Angry
      - [x] Surprised
      - [x] Happy
      - [x] Smug
      - [x] Embarrassed
      - [ ] Horny (?)
    - [ ] Profile picture for messenger (any style that expresses the character)
    - [ ] Sitting at table
      - [ ] Angry
      - [ ] Surprised
      - [ ] Happy
      - [ ] Smug
      - [ ] Embarrassed
      - [ ] Horny (?)
  - [ ] Emma
    - [ ] Visual novel style
      - [ ] Angry
      - [ ] Surprised
      - [ ] Happy
      - [ ] Smug
      - [ ] Embarrassed
      - [ ] Horny (?)
    - [ ] Profile picture for messenger (any style that expresses the character)
    - [ ] Sitting at table
      - [ ] Angry
      - [ ] Surprised
      - [ ] Happy
      - [ ] Smug
      - [ ] Embarrassed
      - [ ] Horny (?)
  - [ ] Maya
    - [ ] Visual novel style
      - [x] Angry
      - [ ] Surprised
      - [ ] Happy
      - [ ] Smug
      - [ ] Embarrassed
      - [ ] Horny (?)
    - [ ] Profile picture for messenger (any style that expresses the character)
    - [ ] Sitting at table
      - [ ] Angry
      - [ ] Surprised
      - [ ] Happy
      - [ ] Smug
      - [ ] Embarrassed
      - [ ] Horny (?)
  - [ ] Art for "ingame characters" (non-player characters)
    - [ ] Various character designs
    - [ ] Dwarf, elf, wizard, can be VERY poorly drawn as they are drawn by ingame people
  - [ ] Art of table, with room for speech bubbles and "events"
  - [ ] Art of NPCs sitting at table, with various reactions
- [ ] DM cards art
  - [ ] Art for "cards" DM will play to challenge party
  - [ ] health potion
  - [ ] Owlbear attack
  - [ ] mimic trap
  - [ ] puzzle
  - [ ] NPC interaction
  - [ ] shopping
- [ ] Party effects art
  - [ ] Art for effects as party succeeds or fails
