### ISSUE TITLE
Add onboarding checklist

### ISSUE THREAD

**Issue by Achoobert** [Achoobert/game_4#12]
Permissions
- [ ] Project
- [ ] Repo

Add How to tutorial
- [ ] dialogic
- [ ] godot
- [ ] 
Add how to get it to run
Add how to get it downloaded
- [ ] add how to install git
- [ ] add how you should manage your directories
- [ ] add git clone
- [ ] alias tutorial???
-Add commandline to open GD from terminal

add explanation of what windows are plus screenshots of what they should look like
